name: brcode
description: A Dart package to generate Pix (Brazilian Instant Payment) static codes (BR Code). Simple, lightweight, and validated.
version: 0.0.3
homepage: https://github.com/enriquesaid/brcode/
repository: https://github.com/enriquesaid/brcode

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  crclib: ^3.0.0
  diacritic: ^0.1.4
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

topics:
  - pix
  - payment
  - brcode
  - qrcode
  - brazil
